apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: ecommerce
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: inventory-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opentelemetry-javaagent.jar"
        - name: OTEL_SERVICE_NAME
          value: "inventory-service"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://jaeger:4317"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: "http://prometheus:9090/api/v1/otlp/v1/metrics"
        - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        readinessProbe:
          httpGet:
            path: /h2-console
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
