apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contact-points
  namespace: ecommerce
data:
  contact-points.yaml: |
    apiVersion: 1

    contactPoints:
      - orgId: 1
        name: ecommerce-webhook
        receivers:
          - uid: webhook-sink
            type: webhook
            disableResolveMessage: false
            settings:
              url: http://webhook-sink:8080/grafana-alerts
              httpMethod: POST
              maxAlerts: '0'
